# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0003_auto_20170517_2138'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gist', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_itmes', to='restaurant.Item')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_offers', to='offer.Offer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending', to='restaurant.Restaurant')),
            ],
        ),
    ]
